<?php
$pageTitle = "Home";

require_once('inc/header.php');
?>

<p>Please click one of the above links to convert a measurement.</p>
<p><em>Note: Only SI base units used, consult the table below for SI prefixes.</em></p>
<table>
    <thead>
    <tr>
        <th>Prefix</th>
        <th>Symbol</th>
        <th>Base 10</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>yotta</td>
        <td>Y</td>
        <td>10<sup>24</sup></td>
    </tr>
    <tr>
        <td>zetta</td>
        <td>Z</td>
        <td>10<sup>21</sup></td>
    </tr>
    <tr>
        <td>exa</td>
        <td>E</td>
        <td>10<sup>18</sup></td>
    </tr>
    <tr>
        <td>peta</td>
        <td>P</td>
        <td>10<sup>15</sup></td>
    </tr>
    <tr>
        <td>tera</td>
        <td>T</td>
        <td>10<sup>12</sup></td>
    </tr>
    <tr>
        <td>giga</td>
        <td>G</td>
        <td>10<sup>9</sup></td>
    </tr>
    <tr>
        <td>mega</td>
        <td>M</td>
        <td>10<sup>6</sup></td>
    </tr>
    <tr>
        <td>kilo</td>
        <td>k</td>
        <td>10<sup>3</sup></td>
    </tr>
    <tr>
        <td>hecto</td>
        <td>h</td>
        <td>10<sup>2</sup></td>
    </tr>
    <tr>
        <td>deca</td>
        <td>da</td>
        <td>10<sup>1</sup></td>
    </tr>
    <tr>
        <td>deci</td>
        <td>d</td>
        <td>10<sup>-1</sup></td>
    </tr>
    <tr>
        <td>centi</td>
        <td>c</td>
        <td>10<sup>-2</sup></td>
    </tr>
    <tr>
        <td>milli</td>
        <td>m</td>
        <td>10<sup>-3</sup></td>
    </tr>
    <tr>
        <td>micro</td>
        <td>&mu;</td>
        <td>10<sup>-6</sup></td>
    </tr>
    <tr>
        <td>nano</td>
        <td>n</td>
        <td>10<sup>-9</sup></td>
    </tr>
    <tr>
        <td>pico</td>
        <td>p</td>
        <td>10<sup>-12</sup></td>
    </tr>
    <tr>
        <td>femto</td>
        <td>f</td>
        <td>10<sup>-15</sup></td>
    </tr>
    <tr>
        <td>atto</td>
        <td>a</td>
        <td>10<sup>-18</sup></td>
    </tr>
    <tr>
        <td>zepto</td>
        <td>z</td>
        <td>10<sup>-21</sup></td>
    </tr>
    <tr>
        <td>yocto</td>
        <td>y</td>
        <td>10<sup>-24</sup></td>
    </tr>
    </tbody>
</table>

<?php require_once('inc/footer.php'); ?>
